---
title: "Aggregate PGS p-values"
author: "XSun"
date: "2024-10-27"
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
---

```{r warning=F,message=F}
library(ggplot2)
library(ACAT)
library(dplyr)
library(readxl)
source("/project/xinhe/xsun/r_functions/qqplot_sigle.R")
```

# Introduction

We use ACAT to aggregate the p-values for the traits within a group / for the PGSs from top 10 immune traits.


```{r}
file_path <- "/project/xinhe/xsun/cart/1.pgs/data/MULTIVARIATE_LOGIT_PHENOTYPE_for_XS.xlsx"
num_sheets <- length(excel_sheets(file_path))

allcategroy <- list()
allcategroy_df <- c()
names <- c()
acat_all <- c()
for (i in 2:num_sheets) {
  
  pgs_categroy <- read_xlsx(file_path,sheet = i)
  
  pgs_categroy$P_value[pgs_categroy$P_value == 1] <- 1-1/nrow(pgs_categroy)
  
  acat_group <- ACAT(as.numeric(pgs_categroy$P_value))
  acat_all <- c(acat_all,acat_group)
  
  name_current <- unique(pgs_categroy$Trait_category)[1]
  names <- c(names,name_current)
  
  allcategroy[[i-1]] <- pgs_categroy
  
  allcategroy_df <- rbind(allcategroy_df,pgs_categroy)
}

DT::datatable(allcategroy_df,caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','Table for PGS p-values'),options = list(pageLength = 10) )

```


# Results -- aggregating the p-values for the traits within a group

```{r}

acat_df_all <- data.frame(categroy = names, acat_p = acat_all)
names(allcategroy) <- names

acat_df_all <- acat_df_all[order(as.numeric(acat_df_all$acat_p)),]

DT::datatable(acat_df_all,caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','ACAT p-values for each group'),options = list(pageLength = 10) )


qqplot(as.numeric(acat_df_all$acat_p))
```

The 4 categories with ACAT p-values < 0.05


```{r}

sig_cats <- unique(acat_df_all$categroy[acat_df_all$acat_p < 0.05])

for (i in 1:length(sig_cats)) {
  trait_category <- allcategroy_df$Reported_Trait[allcategroy_df$Trait_category %in% sig_cats[i]]
  trait_list <- paste0("  - ", unique(trait_category), collapse = "\n")
  cat(sprintf("Traits in category %d (%s):\n%s\n\n", i, sig_cats[i], trait_list))
}


groups_acat <- allcategroy_df[allcategroy_df$Trait_category %in% acat_df_all$categroy[acat_df_all$acat_p < 0.05],]
DT::datatable(groups_acat,caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','The 4 groups with ACAT p-values < 0.05'),options = list(pageLength = 10) )

```



# Results -- aggregating the p-values for the PGSs from top 10 immune traits & T2D

## top 10 immune traits

```{r}

file_path <- "/project/xinhe/xsun/cart/1.pgs/data/Modified_List of the top 10 immune diseases.xlsx"

df_top10 <- readxl::read_excel(file_path)

traits <- unique(df_top10$Trait_ontology)
sprintf("the top 10 inmmune traits are %s", paste0(traits,collapse = ", "))

acat_all <- c()
for (i in 1:length(traits)){
  
  trait <- traits[i]
  df_trait <- df_top10[df_top10$Trait_ontology == trait,]
  
  acat_trait <- ACAT(as.numeric(df_trait$P_value))
  acat_all <- c(acat_all,acat_trait)
}

acat_df_all <- data.frame(trait = traits, acat_p = acat_all)

acat_df_all <- acat_df_all[order(as.numeric(acat_df_all$acat_p)),]

DT::datatable(acat_df_all,caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','ACAT p-values for each trait'),options = list(pageLength = 10) )


qqplot(as.numeric(acat_df_all$acat_p))
```

## T1D

```{r}

df_t1d <- read_excel("/project/xinhe/xsun/cart/1.pgs/data/Digestive_Immune_metabolic_disorders_sample_size.xlsx")



DT::datatable(df_t1d,caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','PGS p-values for T1D'),options = list(pageLength = 5) )

sprintf("ACAT p-values for T1D  (all PGS) = %s", round(ACAT(as.numeric(df_t1d$P_value)),digits = 4))

df_t1d_filtered <- df_t1d[df_t1d$Number_of_Individuals < 100000,]
df_t1d_filtered <- df_t1d_filtered[complete.cases(df_t1d_filtered$P_value),]

sprintf("ACAT p-values for T1D (PGS with sample size < 100,000 filtered out) = %s", round(ACAT(as.numeric(df_t1d_filtered$P_value)),digits = 4))

df_t1d_filtered <- df_t1d[df_t1d$Number_of_Individuals < 50000,]
df_t1d_filtered <- df_t1d_filtered[complete.cases(df_t1d_filtered$P_value),]
sprintf("ACAT p-values for T1D  (PGS with sample size < 50,000 filtered out)  = %s", round(ACAT(as.numeric(df_t1d_filtered$P_value)),digits = 4))
```


## T2D

```{r}

df_t2d <- read_excel("/project/xinhe/xsun/cart/1.pgs/data/Digestive_metabolic_T2D_sample_size.xlsx")

df_t2d$P_value[df_t2d$P_value ==1] <- 0.9999

DT::datatable(df_t2d,caption = htmltools::tags$caption( style = 'caption-side: left; text-align: left; color:black;  font-size:150% ;','PGS p-values for T2D'),options = list(pageLength = 5) )

sprintf("ACAT p-values for T2D (all PGS) = %s", round(ACAT(as.numeric(df_t2d$P_value)),digits = 4))


df_t2d_filtered <- df_t2d[df_t2d$Number_of_Individuals < 100000,]
df_t2d_filtered <- df_t2d_filtered[complete.cases(df_t2d_filtered$P_value),]
sprintf("ACAT p-values for T2D (PGS with sample size < 100,000 filtered out) = %s", round(ACAT(as.numeric(df_t2d_filtered$P_value)),digits = 4))


df_t2d_filtered <- df_t2d[df_t2d$Number_of_Individuals < 50000,]
df_t2d_filtered <- df_t2d_filtered[complete.cases(df_t2d_filtered$P_value),]
sprintf("ACAT p-values for T2D (PGS with sample size < 50,000 filtered out) = %s", round(ACAT(as.numeric(df_t2d_filtered$P_value)),digits = 4))
```